# -*- coding: utf-8 -*-

"""
    releansapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from releansapi.api_helper import APIHelper


class BalanceControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(BalanceControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.balance

    # Get your available balance
    def test_balance(self):
        # Parameters for the API call
        accept = 'text/plain'

        # Perform the API call through the SDK function
        result = self.controller.get_balance(accept)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))

        
        # Test whether the captured response is as we expected
        self.assertIsNotNone(result)
        self.assertEqual('{"balance":100}', self.response_catcher.response.raw_body)


