# -*- coding: utf-8 -*-

"""
    releansapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from releansapi.api_helper import APIHelper


class MessageControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(MessageControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.message

    # List all messages sent by the account.
    def test_get_all_messages(self):
        # Parameters for the API call
        accept = '*/*'

        # Perform the API call through the SDK function
        result = self.controller.get_all_messages(accept)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Return the details of the message.
    def test_view_message(self):
        # Parameters for the API call
        id = 'id'
        accept = '*/*'

        # Perform the API call through the SDK function
        result = self.controller.get_view_message(id, accept)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

