# -*- coding: utf-8 -*-

"""
    releansapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from releansapi.decorators import lazy_property
from releansapi.configuration import Configuration
from releansapi.controllers.message_controller import MessageController
from releansapi.controllers.sender_controller import SenderController
from releansapi.controllers.balance_controller import BalanceController


class ReleansapiClient(object):

    config = Configuration

    @lazy_property
    def message(self):
        return MessageController()

    @lazy_property
    def sender(self):
        return SenderController()

    @lazy_property
    def balance(self):
        return BalanceController()


    def __init__(self,
                 o_auth_access_token=None):
        if o_auth_access_token != None:
            Configuration.o_auth_access_token = o_auth_access_token


